### ISSUE TITLE
When block doesn't exist then it gives this error

### ISSUE THREAD

**Issue by sanjaymadane** [Ajnasz/IniReader#12]
TypeError: Cannot read property 'length' of undefined                                                                            
    at IniReaderCore.getParam (/server/node_modules/inireader/lib/inireadercore.js:425:32)                                       
    at IniReaderCore.param (/server/node_modules/inireader/lib/inireadercore.js:491:23)                                          
    at Object.module.exports.getQPKGConfig (/server/auth/nas_auth.js:31:24)                                                      
    at /server/routes/nas_config/index.js:31:14                                                                                  
    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)                                  
    at next (/server/node_modules/express/lib/router/route.js:131:13)                                                            
    at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)                                                   
    at Layer.handle [as handle_request] (/server/node_modules/express/lib/router/layer.js:95:5)                                  
    at /server/node_modules/express/lib/router/index.js:277:22                                                                   
    at Function.process_params (/server/node_modules/express/lib/router/index.js:330:12)                                         
    at next (/server/node_modules/express/lib/router/index.js:271:10)                                                            
    at Function.handle (/server/node_modules/express/lib/router/index.js:176:3)

**Comment by Ajnasz** [comment]
Fixed in 1.1.1

**Comment by sanjaymadane** [comment]
Thanks @Ajnasz
